
import type { User } from '../../types';

export const MOCK_DEMO_USERS: User[] = [
    {
        id: 'demo-master-admin-id',
        uid: 'demo-master-admin-id',
        organizationId: 'demo-org-123',
        firstName: 'Cameron',
        lastName: 'Owner',
        email: 'cameron@summitpeak.demo',
        username: 'cameron_owner',
        role: 'master_admin',
        status: 'active',
        payRate: 0, // Salaried
        payType: 'salary',
        billableRate: 250,
        ptoAccrued: 120,
        hireDate: '2022-01-10',
        profilePicUrl: '/avatars/cameron.jpg',
        preferences: { theme: 'light', notifications: true }
    },
    {
        id: 'demo-admin-id',
        uid: 'demo-admin-id',
        organizationId: 'demo-org-123',
        firstName: 'Alex',
        lastName: 'Admin',
        email: 'alex@summitpeak.demo',
        username: 'alex_admin',
        role: 'admin',
        status: 'active',
        payRate: 28,
        payType: 'hourly',
        billableRate: 150,
        ptoAccrued: 40,
        hireDate: '2022-08-01',
        reportsTo: 'demo-master-admin-id',
        profilePicUrl: '/avatars/alex.jpg',
        preferences: { theme: 'light' }
    },
    {
        id: 'demo-tech-id',
        uid: 'demo-tech-id',
        organizationId: 'demo-org-123',
        firstName: 'Terry',
        lastName: 'Tech',
        email: 'terry@summitpeak.demo',
        username: 'terry_tech',
        role: 'employee',
        status: 'active',
        payRate: 35,
        payType: 'hourly',
        billableRate: 120,
        ptoAccrued: 24,
        hireDate: '2023-03-15',
        digitalId: 'TT-7788',
        profilePicUrl: '/avatars/terry.jpg',
        location: { lat: 39.7392, lng: -104.9903, timestamp: new Date().toISOString() },
        certifications: [{ name: 'NATE Certified', expiryDate: '2025-10-01' }]
    },
    {
        id: 'demo-tech-2-id',
        uid: 'demo-tech-2-id',
        organizationId: 'demo-org-123',
        firstName: 'Brian',
        lastName: 'Mechanic',
        email: 'brian@summitpeak.demo',
        username: 'brian_mechanic',
        role: 'employee',
        status: 'active',
        payRate: 28,
        payType: 'hourly',
        billableRate: 110,
        ptoAccrued: 16,
        hireDate: '2023-09-01',
        digitalId: 'BM-1234',
        profilePicUrl: '/avatars/brian.jpg',
        location: { lat: 39.7522, lng: -105.0011, timestamp: new Date().toISOString() }
    },
    {
        id: 'demo-customer-user-id',
        uid: 'demo-customer-user-id',
        organizationId: 'demo-org-123',
        firstName: 'Jordan',
        lastName: 'Homeowner',
        email: 'jordan@demo.com',
        username: 'jordan_h',
        role: 'customer',
        status: 'active',
        payRate: 0,
        ptoAccrued: 0
    },
    {
        id: 'demo-sales-id',
        uid: 'demo-sales-id',
        organizationId: 'platform',
        firstName: 'Sam',
        lastName: 'Sales',
        email: 'sales@tektrakker.com',
        username: 'sam_sales',
        role: 'platform_sales',
        status: 'active',
        payRate: 0, // Commission based
        ptoAccrued: 0,
        profilePicUrl: '/avatars/sam.jpg'
    }
];
