export interface StateTaxRule {
    code: string;
    name: string;
    agency: string;
    formName: string;
    defaultStateRate: number;
    defaultLocalRate: number;
    timelyDiscountPercent: number;
    timelyDiscountCap?: number;
    noSalesTax?: boolean;
    residentialLaborTaxable: boolean;
    commercialLaborTaxable: boolean;
    contractorNotes: string;
}

export const US_STATE_TAX_RULES: Record<string, StateTaxRule> = {
    AL: {
        code: 'AL',
        name: 'Alabama',
        agency: 'Alabama Department of Revenue (MAT)',
        formName: 'Form 2100 (State Sales Tax Return)',
        defaultStateRate: 4.0,
        defaultLocalRate: 5.25,
        timelyDiscountPercent: 5.0, // 5% of first $100, 2% thereafter
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Installation/repair labor non-taxable if separately stated on invoice.'
    },
    AK: {
        code: 'AK',
        name: 'Alaska',
        agency: 'Alaska Municipal Sales Tax Program',
        formName: 'Local Borough Return',
        defaultStateRate: 0.0,
        defaultLocalRate: 1.75,
        timelyDiscountPercent: 0.0,
        noSalesTax: true,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'No state sales tax. Municipalities may levy local sales tax.'
    },
    AZ: {
        code: 'AZ',
        name: 'Arizona',
        agency: 'Arizona Department of Revenue (AZTaxes)',
        formName: 'Form TPT-2 (Transaction Privilege Tax)',
        defaultStateRate: 5.6,
        defaultLocalRate: 2.8,
        timelyDiscountPercent: 1.2,
        residentialLaborTaxable: false,
        commercialLaborTaxable: true,
        contractorNotes: 'Prime contracting TPT applies to modification/commercial construction.'
    },
    AR: {
        code: 'AR',
        name: 'Arkansas',
        agency: 'Arkansas Department of Finance and Administration (ATAP)',
        formName: 'Form ET-1 (Excise Tax Return)',
        defaultStateRate: 6.5,
        defaultLocalRate: 2.9,
        timelyDiscountPercent: 2.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Repair and installation labor services are taxable in Arkansas.'
    },
    CA: {
        code: 'CA',
        name: 'California',
        agency: 'California Department of Tax and Fee Administration (CDTFA)',
        formName: 'Form CDTFA-401 (State, Local, & District Tax Return)',
        defaultStateRate: 7.25,
        defaultLocalRate: 1.5,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor to repair or install property is non-taxable if itemized.'
    },
    CO: {
        code: 'CO',
        name: 'Colorado',
        agency: 'Colorado Department of Revenue (SUTS)',
        formName: 'Form DR 0100 (Retail Sales Tax Return)',
        defaultStateRate: 2.9,
        defaultLocalRate: 4.8,
        timelyDiscountPercent: 4.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor is non-taxable if separately stated from materials.'
    },
    CT: {
        code: 'CT',
        name: 'Connecticut',
        agency: 'Connecticut Department of Revenue Services (myconneCT)',
        formName: 'Form OS-114 (Sales and Use Tax Return)',
        defaultStateRate: 6.35,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Repair and maintenance labor services on real property are taxable.'
    },
    DE: {
        code: 'DE',
        name: 'Delaware',
        agency: 'Delaware Division of Revenue',
        formName: 'Gross Receipts Tax Return',
        defaultStateRate: 0.0,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.0,
        noSalesTax: true,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'No state sales tax. Contractors pay Delaware Gross Receipts Tax.'
    },
    FL: {
        code: 'FL',
        name: 'Florida',
        agency: 'Florida Department of Revenue',
        formName: 'Form DR-15 (Sales and Use Tax Return)',
        defaultStateRate: 6.0,
        defaultLocalRate: 1.0,
        timelyDiscountPercent: 2.5,
        timelyDiscountCap: 30.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Real property improvement labor non-taxable under retail/resale contract rules.'
    },
    GA: {
        code: 'GA',
        name: 'Georgia',
        agency: 'Georgia Department of Revenue (GTC)',
        formName: 'Form ST-3 (Sales and Use Tax Return)',
        defaultStateRate: 4.0,
        defaultLocalRate: 3.5,
        timelyDiscountPercent: 0.5,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor for real property repairs is non-taxable if itemized.'
    },
    HI: {
        code: 'HI',
        name: 'Hawaii',
        agency: 'Hawaii Department of Taxation (Hawaii Tax Online)',
        formName: 'Form G-45 (General Excise Tax Return)',
        defaultStateRate: 4.0,
        defaultLocalRate: 0.5,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Hawaii GET applies to all business activities including services & labor.'
    },
    ID: {
        code: 'ID',
        name: 'Idaho',
        agency: 'Idaho State Tax Commission (TAP)',
        formName: 'Form Form 850 (Sales & Use Tax Return)',
        defaultStateRate: 6.0,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Installation & repair labor is non-taxable if itemized.'
    },
    IL: {
        code: 'IL',
        name: 'Illinois',
        agency: 'Illinois Department of Revenue (MyTax Illinois)',
        formName: 'Form ST-1 (Sales and Use Tax Return)',
        defaultStateRate: 6.25,
        defaultLocalRate: 2.5,
        timelyDiscountPercent: 1.75,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Contractors are consumers of materials. Labor is non-taxable if itemized.'
    },
    IN: {
        code: 'IN',
        name: 'Indiana',
        agency: 'Indiana Department of Revenue (INTIME)',
        formName: 'Form ST-103 (Sales Tax Return)',
        defaultStateRate: 7.0,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.73,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor to improve real property is non-taxable if stated separately.'
    },
    IA: {
        code: 'IA',
        name: 'Iowa',
        agency: 'Iowa Department of Revenue (GovConnectIowa)',
        formName: 'Form 32-001 (Sales Tax Return)',
        defaultStateRate: 6.0,
        defaultLocalRate: 1.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'HVAC repair & maintenance services are taxable services in Iowa.'
    },
    KS: {
        code: 'KS',
        name: 'Kansas',
        agency: 'Kansas Department of Revenue (Kansas WebTax)',
        formName: 'Form ST-36 (Sales Tax Return)',
        defaultStateRate: 6.5,
        defaultLocalRate: 2.2,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Labor services to install or repair property are generally taxable.'
    },
    KY: {
        code: 'KY',
        name: 'Kentucky',
        agency: 'Kentucky Department of Revenue (WRAPS)',
        formName: 'Form 51A102 (Sales and Use Tax Return)',
        defaultStateRate: 6.0,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 1.75,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor for real property repair/remodel is generally non-taxable.'
    },
    LA: {
        code: 'LA',
        name: 'Louisiana',
        agency: 'Louisiana Department of Revenue (LaTAP)',
        formName: 'Form R-1029 (Sales Tax Return)',
        defaultStateRate: 4.45,
        defaultLocalRate: 5.0,
        timelyDiscountPercent: 0.935,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor for real property repairs is non-taxable if itemized.'
    },
    ME: {
        code: 'ME',
        name: 'Maine',
        agency: 'Maine Revenue Services (I-File)',
        formName: 'Form ST-7 (Sales and Use Tax Return)',
        defaultStateRate: 5.5,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor for repair/installation is non-taxable if itemized.'
    },
    MD: {
        code: 'MD',
        name: 'Maryland',
        agency: 'Comptroller of Maryland (bFile)',
        formName: 'Form 202 (Sales and Use Tax Return)',
        defaultStateRate: 6.0,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.6,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Real property improvement labor is non-taxable.'
    },
    MA: {
        code: 'MA',
        name: 'Massachusetts',
        agency: 'Massachusetts Department of Revenue (MassTaxConnect)',
        formName: 'Form ST-9 (Sales and Use Tax Return)',
        defaultStateRate: 6.25,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor for installation/repair is non-taxable if itemized.'
    },
    MI: {
        code: 'MI',
        name: 'Michigan',
        agency: 'Michigan Department of Treasury (Michigan Treasury Online)',
        formName: 'Form 5080 (Sales Tax Return)',
        defaultStateRate: 6.0,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.75,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Real property labor is non-taxable if itemized.'
    },
    MN: {
        code: 'MN',
        name: 'Minnesota',
        agency: 'Minnesota Department of Revenue (e-Services)',
        formName: 'Form ST3 (Sales and Use Tax Return)',
        defaultStateRate: 6.875,
        defaultLocalRate: 1.5,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor for real property repair/remodel is non-taxable.'
    },
    MS: {
        code: 'MS',
        name: 'Mississippi',
        agency: 'Mississippi Department of Revenue (TAP)',
        formName: 'Form 72-010 (Sales Tax Return)',
        defaultStateRate: 7.0,
        defaultLocalRate: 0.25,
        timelyDiscountPercent: 2.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Contractor tax applies at 3.5% or regular 7% sales tax on repairs.'
    },
    MO: {
        code: 'MO',
        name: 'Missouri',
        agency: 'Missouri Department of Revenue (MyTax Missouri)',
        formName: 'Form 53-1 (Sales Tax Return)',
        defaultStateRate: 4.225,
        defaultLocalRate: 3.8,
        timelyDiscountPercent: 2.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor to install or repair real property is non-taxable if itemized.'
    },
    MT: {
        code: 'MT',
        name: 'Montana',
        agency: 'Montana Department of Revenue (TransAction Portal)',
        formName: 'Resort Tax Return',
        defaultStateRate: 0.0,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.0,
        noSalesTax: true,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'No state sales tax in Montana.'
    },
    NE: {
        code: 'NE',
        name: 'Nebraska',
        agency: 'Nebraska Department of Revenue (NebFile)',
        formName: 'Form 10 (Sales and Use Tax Return)',
        defaultStateRate: 5.5,
        defaultLocalRate: 1.5,
        timelyDiscountPercent: 2.5,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Option 1/2 contractor rules apply. Repair labor is generally taxable.'
    },
    NV: {
        code: 'NV',
        name: 'Nevada',
        agency: 'Nevada Department of Taxation (Nevada Tax)',
        formName: 'Form TXR-01.01 (Sales Tax Return)',
        defaultStateRate: 6.85,
        defaultLocalRate: 1.53,
        timelyDiscountPercent: 0.25,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Installation & repair labor is non-taxable if itemized.'
    },
    NH: {
        code: 'NH',
        name: 'New Hampshire',
        agency: 'New Hampshire Department of Revenue Administration',
        formName: 'Meals & Rentals Return',
        defaultStateRate: 0.0,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.0,
        noSalesTax: true,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'No state sales tax on labor or materials in New Hampshire.'
    },
    NJ: {
        code: 'NJ',
        name: 'New Jersey',
        agency: 'New Jersey Division of Taxation (Premier Business Services)',
        formName: 'Form ST-50 (Sales Tax Return)',
        defaultStateRate: 6.625,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Capital improvement labor non-taxable with ST-8; repair labor is taxable.'
    },
    NM: {
        code: 'NM',
        name: 'New Mexico',
        agency: 'New Mexico Taxation and Revenue Department (TAP)',
        formName: 'Form CRS-1 (Gross Receipts Tax)',
        defaultStateRate: 4.875,
        defaultLocalRate: 2.75,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Gross Receipts Tax (GRT) applies to both labor & materials.'
    },
    NY: {
        code: 'NY',
        name: 'New York',
        agency: 'New York State Department of Taxation and Finance',
        formName: 'Form ST-100 / ST-101 (Sales Tax Return)',
        defaultStateRate: 4.0,
        defaultLocalRate: 4.875,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Capital improvements exempt with ST-124; repairs & maintenance labor taxable.'
    },
    NC: {
        code: 'NC',
        name: 'North Carolina',
        agency: 'North Carolina Department of Revenue (eNC3)',
        formName: 'Form E-500 (Sales and Use Tax Return)',
        defaultStateRate: 4.75,
        defaultLocalRate: 2.25,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Repair, maintenance, and installation (RMI) services are taxable.'
    },
    ND: {
        code: 'ND',
        name: 'North Dakota',
        agency: 'North Dakota Office of State Tax Commissioner (TAP)',
        formName: 'Form ST (Sales and Use Tax Return)',
        defaultStateRate: 5.0,
        defaultLocalRate: 2.0,
        timelyDiscountPercent: 1.5,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor for real property improvements is non-taxable.'
    },
    OH: {
        code: 'OH',
        name: 'Ohio',
        agency: 'Ohio Department of Taxation (Ohio Business Gateway)',
        formName: 'Form UST-1 (Sales Tax Return)',
        defaultStateRate: 5.75,
        defaultLocalRate: 2.0,
        timelyDiscountPercent: 0.75,
        residentialLaborTaxable: false,
        commercialLaborTaxable: true,
        contractorNotes: 'Commercial repair labor is taxable; residential repair labor is non-taxable.'
    },
    OK: {
        code: 'OK',
        name: 'Oklahoma',
        agency: 'Oklahoma Tax Commission (OkTAP)',
        formName: 'Form STS-20002 (Sales Tax Return)',
        defaultStateRate: 4.5,
        defaultLocalRate: 4.5,
        timelyDiscountPercent: 1.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Real property improvement labor is non-taxable.'
    },
    OR: {
        code: 'OR',
        name: 'Oregon',
        agency: 'Oregon Department of Revenue',
        formName: 'Corporate Activity Tax Return',
        defaultStateRate: 0.0,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.0,
        noSalesTax: true,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'No state sales tax in Oregon.'
    },
    PA: {
        code: 'PA',
        name: 'Pennsylvania',
        agency: 'Pennsylvania Department of Revenue (myPATH)',
        formName: 'Form REV-1500 (Sales & Use Tax Return)',
        defaultStateRate: 6.0,
        defaultLocalRate: 1.0,
        timelyDiscountPercent: 1.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: true,
        contractorNotes: 'Commercial maintenance & repair labor taxable; residential repair labor non-taxable.'
    },
    RI: {
        code: 'RI',
        name: 'Rhode Island',
        agency: 'Rhode Island Division of Taxation (Tax Portal)',
        formName: 'Form T-204 (Sales Tax Return)',
        defaultStateRate: 7.0,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor for real property repairs is non-taxable if itemized.'
    },
    SC: {
        code: 'SC',
        name: 'South Carolina',
        agency: 'South Carolina Department of Revenue (MyDORWAY)',
        formName: 'Form ST-3 (Sales Tax Return)',
        defaultStateRate: 6.0,
        defaultLocalRate: 1.5,
        timelyDiscountPercent: 3.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Real property labor is non-taxable.'
    },
    SD: {
        code: 'SD',
        name: 'South Dakota',
        agency: 'South Dakota Department of Revenue (E-Path)',
        formName: 'Form 4001 (Sales & Contractor Tax Return)',
        defaultStateRate: 4.2,
        defaultLocalRate: 2.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Contractors Excise Tax (2%) applies to construction & repair labor.'
    },
    TN: {
        code: 'TN',
        name: 'Tennessee',
        agency: 'Tennessee Department of Revenue (TNTAP)',
        formName: 'Form SLS-450 (Sales Tax Return)',
        defaultStateRate: 7.0,
        defaultLocalRate: 2.75,
        timelyDiscountPercent: 2.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor for real property repairs is non-taxable if itemized.'
    },
    TX: {
        code: 'TX',
        name: 'Texas',
        agency: 'Texas Comptroller of Public Accounts (WebFile)',
        formName: 'Form 01-114 / 01-116',
        defaultStateRate: 6.25,
        defaultLocalRate: 2.0,
        timelyDiscountPercent: 0.5,
        residentialLaborTaxable: false,
        commercialLaborTaxable: true,
        contractorNotes: 'Residential repair labor exempt. Commercial repair labor taxable. Tax-paid material credit allowed.'
    },
    UT: {
        code: 'UT',
        name: 'Utah',
        agency: 'Utah State Tax Commission (TAP)',
        formName: 'Form TC-62M (Sales Tax Return)',
        defaultStateRate: 4.85,
        defaultLocalRate: 2.3,
        timelyDiscountPercent: 1.2,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor to convert personal property into real property is non-taxable.'
    },
    VT: {
        code: 'VT',
        name: 'Vermont',
        agency: 'Vermont Department of Taxes (myVTax)',
        formName: 'Form SBR-431 (Sales & Use Tax Return)',
        defaultStateRate: 6.0,
        defaultLocalRate: 1.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Real property installation & repair labor is non-taxable.'
    },
    VA: {
        code: 'VA',
        name: 'Virginia',
        agency: 'Virginia Department of Taxation (VATAX)',
        formName: 'Form ST-9 (Sales and Use Tax Return)',
        defaultStateRate: 4.3,
        defaultLocalRate: 1.0,
        timelyDiscountPercent: 1.6,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Real property labor is non-taxable if itemized.'
    },
    WA: {
        code: 'WA',
        name: 'Washington',
        agency: 'Washington Department of Revenue (My DOR)',
        formName: 'Combined Excise Tax Return',
        defaultStateRate: 6.5,
        defaultLocalRate: 2.8,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Custom construction & repair labor is subject to retail sales tax.'
    },
    WV: {
        code: 'WV',
        name: 'West Virginia',
        agency: 'West Virginia State Tax Department (MyTaxes)',
        formName: 'Form CST-200CU (Sales Tax Return)',
        defaultStateRate: 6.0,
        defaultLocalRate: 1.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'Contracting services generally exempt, but repair labor is taxable.'
    },
    WI: {
        code: 'WI',
        name: 'Wisconsin',
        agency: 'Wisconsin Department of Revenue (My Tax Account)',
        formName: 'Form S-108 (Sales Tax Return)',
        defaultStateRate: 5.0,
        defaultLocalRate: 0.5,
        timelyDiscountPercent: 0.5,
        residentialLaborTaxable: true,
        commercialLaborTaxable: true,
        contractorNotes: 'HVAC installation and repair labor is a taxable service in Wisconsin.'
    },
    WY: {
        code: 'WY',
        name: 'Wyoming',
        agency: 'Wyoming Department of Revenue (WYIFS)',
        formName: 'Form 410 (Sales Tax Return)',
        defaultStateRate: 4.0,
        defaultLocalRate: 2.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Labor to improve real property is non-taxable.'
    },
    DC: {
        code: 'DC',
        name: 'District of Columbia',
        agency: 'DC Office of Tax and Revenue (MyTax DC)',
        formName: 'Form FR-800M (Sales & Use Tax Return)',
        defaultStateRate: 6.0,
        defaultLocalRate: 0.0,
        timelyDiscountPercent: 0.0,
        residentialLaborTaxable: false,
        commercialLaborTaxable: false,
        contractorNotes: 'Real property repair labor is non-taxable.'
    }
};
