import React from 'react';
import type { Project, Customer } from 'types';
import { Box, Printer, Mail } from 'lucide-react';
import Button from 'components/ui/Button';
import { sendEmail } from 'lib/notificationService';
import { useAppContext } from 'context/AppContext';
import showToast from "lib/toast";
import { getBaseUrl } from "lib/utils";
import EquipmentHierarchy from './equipment/EquipmentHierarchy';

interface EquipmentTabProps {
    project: Project;
    customer?: Customer;
}

const EquipmentTab: React.FC<EquipmentTabProps> = ({ project, customer }) => {
    const { state } = useAppContext();

    if (!customer) {
        return (
            <div className="p-6 text-center text-gray-500 bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
                <p>No customer linked to this project or customer not found.</p>
            </div>
        );
    }

    const handleSendReport = async () => {
        const reportUrl = `${getBaseUrl()}/#/report/equipment/${customer.id}`;
        
        let targetEmail = customer.email;
        if (!targetEmail) {
            const promptedEmail = window.prompt("Customer has no email on file. Enter email address to deliver report to:");
            if (!promptedEmail) return;
            targetEmail = promptedEmail;
        } else {
            const confirmEmail = window.confirm(`Send equipment health report to ${targetEmail}?`);
            if (!confirmEmail) return;
        }

        try {
            await sendEmail(state.currentOrganization, {
                to: targetEmail,
                message: {
                    subject: `Project Equipment Health Report for ${customer.name}`,
                    html: `
                        <div style="font-family: sans-serif; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #eee; border-radius: 8px; overflow: hidden;">
                            <div style="background-color: #0f172a; padding: 20px; text-align: center; color: white;">
                                <h1 style="margin: 0; font-size: 24px;">Project Equipment Health Report</h1>
                            </div>
                            <div style="padding: 20px; background-color: #fafafa;">
                                <p style="font-size: 16px;">Hello <strong>${customer.name}</strong>,</p>
                                <p style="font-size: 16px; line-height: 1.5;">A new equipment health report has been generated for your project. Please click the secure link below to view your full documentation, including condition assessments, asset data, and corresponding photos.</p>
                                <div style="text-align: center; margin: 40px 0;">
                                    <a href="${reportUrl}" style="background-color: #4f46e5; color: white; padding: 14px 28px; text-decoration: none; border-radius: 6px; font-weight: bold; font-size: 16px; display: inline-block;">View Secure Report</a>
                                </div>
                                <hr style="border: 0; border-top: 1px solid #eee; margin-top: 40px;" />
                                <p style="font-size: 12px; color: #999; margin-top: 20px; text-align: center;">This report was securely generated by TekTrakker on behalf of ${state.currentOrganization?.name || 'your service provider'}.</p>
                            </div>
                        </div>
                    `
                }
            });
            showToast.warn("Report dynamically generated and securely delivered!");
        } catch (error) {
            console.error(error);
            showToast.warn("Failed to send report.");
        }
    };

    return (
        <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
            <div className="flex justify-between items-center mb-6">
                <h3 className="font-bold text-lg text-slate-900 dark:text-white flex items-center gap-2"><Box className="text-blue-500" /> Customer Equipment</h3>
                <div className="flex gap-2">
                    <Button onClick={handleSendReport} className="flex items-center gap-2" variant="primary" size="sm"><Mail size={14}/> Email Report</Button>
                    <Button onClick={() => window.open(`#/report/equipment/${customer.id}`, '_blank')} className="flex items-center gap-2" variant="secondary" size="sm"><Printer size={14}/> View Link</Button>
                </div>
            </div>
            
            <EquipmentHierarchy customer={customer} />
        </div>
    );
};

export default EquipmentTab;
