
import type { InvoiceDetails, InvoicePaymentRecord, InvoiceRefundRecord } from '../types/invoice';
import type { StoredFile } from '../types/file';
import type { ToolReading } from '../types/tool';
import type { Address } from '../types/organization';
import type { InspectionTemplate, BusinessDocument } from '../types';

export interface Job {
  archived?: boolean;
  archivedAt?: string | null;
  archivedBy?: string | null;
  deleted?: boolean;
  deletedAt?: string;
  discrepancyDismissed?: boolean;
  hideRolledInNotice?: boolean;
  id: string;
  organizationId: string;
  assignedPartnerId?: string | null; 
  partnerAllowDirectPayment?: boolean | null;
  customerName: string;
  firstName?: string | null;
  lastName?: string | null;
  address: string | Address;
  city?: string | null;
  state?: string | null;
  zip?: string | null;
  serviceLocationCity?: string | null;
  serviceLocationState?: string | null;
  serviceLocationZip?: string | null;
  serviceLocationAddress?: string | null;
  tasks: string[];
  customerId?: string | null;
  locationId?: string | null;
  locationName?: string | null;
  poNumber?: string | null;
  customerPhone?: string | null;
  customerEmail?: string | null;
  jobStatus: 'Scheduled' | 'In Progress' | 'Diagnosing' | 'Awaiting Customer Approval' | 'Needs Review' | 'Completed' | 'Cancelled' | 'Needs Follow-up';
  needsAdminVerification?: boolean;
  verificationOutcome?: {
    outcome: 'Repair Verified — Operating Properly' | 'Repair Completed — Additional Concern Found' | 'Temporary Repair Only' | 'Unable to Verify' | 'Equipment Not Operational' | 'Return Visit Required';
    tempSplit?: string;
    electricalReadings?: string;
    refrigerantReadings?: string;
    drainOperation?: 'Pass' | 'Fail' | 'N/A';
    thermostatOperation?: 'Pass' | 'Fail' | 'N/A';
    safetyControlOperation?: 'Pass' | 'Fail' | 'N/A';
    finalNotes?: string;
    verifiedBy?: string;
    verifiedAt?: string;
  };
  signOffException?: {
    reason: 'Customer Not Present' | 'Unattended Property' | 'Commercial Work Order' | 'Remote PM Approval' | 'Customer Declined' | 'Remote Approval Documented';
    customerPresenceStatus: 'Not Present' | 'Present - Declined' | 'Property Unattended' | 'Authorized Representative';
    approvalMethod?: string;
    technicianName: string;
    timestamp: string;
    notes?: string;
  };
  reopenHistory?: Array<{
    reopenedAt: string;
    reopenedById: string;
    reopenedByName: string;
    reason: string;
    snapshot: any;
  }>;
  repairPostponed?: boolean;
  repairPostponedReason?: string;
  proposalId?: string | null;
  appointmentTime: string; 
  specialInstructions: string;
  assignedTechnicianId?: string | null;
  assignedTechnicianName?: string | null;
  assignedCrew?: string[];
  assistants?: string[];
  workOrderNumber?: string | null;
  jobNumber?: string | null;
  signatureMetadata?: any;
  signatureHistory?: any[];
  signatureUrl?: string | null;
  jobRecordSignedOff?: boolean;
  jobRecordSignedOffAt?: string;
  jobRecordSignedOffBy?: string;
  jobRecordSignedOffNotes?: string;
  signOff?: any;
  signOffSheetUrl?: string | null;
  signoffSheetUrl?: string | null;
  customWorkOrderFormUrl?: string | null;
  signOffSignature?: string | null;
  customerSignature?: string | null;
  customerSignatureName?: string | null;
  siteManagerSignature?: string | null;
  siteManagerName?: string | null;
  techSignature?: string | null;
  techSignatureName?: string | null;
  signature?: string | null;
  signerName?: string | null;
  signatureTimestamp?: string | null;
  signedAt?: string | null;
  workflowState?: any;
  invoice?: InvoiceDetails | null;
  invoiceSignature?: string | null;
  invoiceSignedDate?: string | null;
  jobEvents: any[];
  notes?: {
      preRepair?: string;
      workNotes?: string;
      completion?: string;
      feedback?: string;
      employeeFeedback?: string;
      customerFeedback?: string;
      checklist?: string;
      internalNotes?: string;
      diagnosisChecklist?: string;
      qualityChecklist?: string;
      arrival?: string;
      diagnosis?: string;
      work?: string;
      thankYouNote?: string;
  };
  source?: string | null;
  hvacType?: string | null;
  hvacBrand?: string | null;
  projectId?: string | null;
  linkedProposalIds?: string[];
  divisionId?: string | null;
  createdAt?: string;
  createdById?: string;
  createdByName?: string;
  updatedAt?: string;
  updatedById?: string;
  updatedByName?: string;
  toolReadings?: ToolReading[];
  files?: StoredFile[];
  refrigerantLog?: any[]; 
  salesRepId?: string;
  total?: number; 
  paidAmount?: number;
  tipAmount?: number;
  payments?: InvoicePaymentRecord[];
  refunds?: InvoiceRefundRecord[];
  amountRefunded?: number;
  netPaid?: number;
  processedPaymentIntentIds?: string[];
  requiredWaiverIds?: string[];
  requiredDiagnosisChecklistIds?: string[];
  requiredQualityChecklistIds?: string[];
  customerFeedback?: string;
  depositType?: 'flat' | 'percentage' | 'none';
  depositValue?: number;
  depositAmount?: number;
  depositRequired?: number;
  depositNotes?: string;
  depositPaid?: boolean;
  depositPaidAmount?: number;
  depositPaidDate?: string;
  isPaymentRequest?: boolean;
  paymentRequestId?: string;
  endTime?: string;
  checkInTime?: string;
  checkOutTime?: string;
  transitStartTime?: string;
  timeOnSiteMinutes?: number;
  timeEntries?: Array<{
    checkInTime: string;
    checkOutTime?: string | null;
    timeOnSiteMinutes?: number | null;
  }>;
  linkedJobIds?: string[];
  linkedInvoiceIds?: string[];
  parentJobId?: string | null;
  isFollowUp?: boolean;
  isServicePlan?: boolean | null;
  servicePlanType?: 'membership' | 'maintenanceAgreement' | string | null;
  servicePlanId?: string | null;


  // Added for B2B document sharing
  embeddedData?: {
    inspectionTemplates?: any[];
    waivers?: any[];
  };
  partsUsed?: Array<{
    id: string;
    name: string;
    sku?: string;
    quantity: number;
    unitPrice?: number;
    total?: number;
    location?: string;
  }>;
  qcAudits?: Array<{
    id: string;
    status: 'pass' | 'fail' | 'warning' | 'manual';
    comments: string;
    timestamp: string;
    imageUrl?: string;
  }>;
  techRecommendations?: string;
  visitType?: 'Diagnostic Only' | 'Diagnostic & Repair' | 'Diagnostic & Troubleshooting' | 'Repair' | 'Maintenance' | 'Service Call' | 'Emergency Repair (No Heat / No AC / Leak)' | 'Request for Proposal (RFP) / Capital Quote' | 'Scheduled Component Repair' | 'Seasonal Maintenance & Comprehensive Tune-Up' | 'System Installation & Retrofit' | 'Warranty Recall & Follow-Up Service' | 'Safety & Code Compliance Inspection' | 'Other' | string;
  includedUnitIds?: string[];
  unitStates?: Array<{
    assetId: string;
    includeOnWorkOrder?: boolean;
    health?: 'Good' | 'Fair' | 'Poor' | 'Critical';
    healthBefore?: 'Good' | 'Fair' | 'Poor' | 'Critical';
    healthAfter?: 'Good' | 'Fair' | 'Poor' | 'Critical';
    diagnosis?: string;
    repair?: string;
    recommendations?: string;
    refrigerantType?: string;
    make?: string;
    model?: string;
    serialNumber?: string;
    mfd?: string;
    systemType?: string;
    location?: string;
  }>;
  subcontractorWorkOrder?: {
    nte: number;
    ivrPin: string;
    ivrNumber: string;
    visitInstructions: string[];
    specialInstructions: string;
    terms: string[];
    createdAt?: string;
    sentAt?: string;
    composedById?: string;
    composedByName?: string;
    subcontractorId?: string;
    status?: 'pending' | 'accepted' | 'declined';
    availabilityWindow?: {
      date: string;
      startTime: string;
      endTime: string;
      notes?: string;
    };
    organization?: {
      name: string;
      phone: string;
      address: string;
      logoUrl?: string;
    };
  };
  subcontractorId?: string | null;
}

