import type { Address } from './organization';

export interface EmployeeDocument {
  id: string;
  organizationId: string;
  fileName: string;
  label: string;
  dataUrl: string; 
  createdAt?: string;
  fileType?: string;
  isVisibleToEmployee?: boolean;
  uploadedBy?: string;
  tags?: string[];
  description?: string;
}

export interface User {
  id: string;
  organizationId: string; 
  uid?: string; 
  username: string;
  email?: string | null; 
  password?: string | null; 
  firstName: string;
  lastName: string;
  payRate: number | string; 
  payType?: 'hourly' | 'salary'; 
  billableRate?: number | null; 
  ptoAccrued: number; 
  role: 'master_admin' | 'franchise_admin' | 'admin' | 'employee' | 'both' | 'customer' | 'supervisor' | 'platform_sales' | 'Technician' | 'Subcontractor'; 
  franchiseId?: string;
  dispatchTeamIds?: string[];
  reportsTo?: string | null; 
  hireDate?: string | null;
  ssn?: string | null; 
  taxId?: string;
  experienceYears?: number | null;
  emergencyContact?: { name: string; phone: string; relationship?: string; alternatePhone?: string; };
  certifications?: { name: string; number?: string; expiryDate?: string; fileUrl?: string; }[];
  ptoAccrualRate?: number | null; 
  mileageRate?: number | null; 
  hasCompanyVehicle?: boolean | null;
  dob?: string;
  driversLicense?: { number: string; state: string; expiryDate: string; };
  employmentType?: 'Full-Time' | 'Part-Time' | 'Temporary';
  department?: string;
  directDeposit?: {
    preference?: 'Direct Deposit' | 'Paper Check';
    bankName?: string;
    accountType?: 'Checking' | 'Savings';
    routingNumber?: string;
    accountNumber?: string;
    effectiveDate?: string;
  };
  infoSheetSignature?: { signature: string; date: string; };
  documents?: EmployeeDocument[]; 
  status?: 'active' | 'archived';
  phone?: string | null;
  address?: Address;
  certificationDate?: string | null;
  otherCertifications?: string | null;
  notes?: string | null;
  cashBalance?: number | null; 
  handbookSignedDate?: string | null;
  location?: { lat: number; lng: number; timestamp: string; };
  lastLocationUpdate?: string | null;
  lastLoginAt?: string | null; 
  preferences?: any;
  permissions?: string[]; 
  marketingConsent?: { sms: boolean; email: boolean; agreedAt: string; source: string; ip?: string; gclid?: string; };
  signedPolicies?: Record<string, string>;
  policySignatures?: Record<string, string>;
  formSubmissions?: Record<string, any>;
  digitalId?: string;
  salesContractSigned?: boolean;
  salesContractDate?: string;
  salesContractSignature?: string;
  salesContractContent?: string;
  taxW9Content?: string;
  profilePicUrl?: string;
  emailSignatureHtml?: string;
  aiEstimatorEnabled?: boolean;
  w4Status?: 'Single' | 'Married' | 'Head of Household';
  w4DependentsAmount?: number;
  w4OtherIncome?: number;
  w4Deductions?: number;
  w4ExtraWithholding?: number;
  weeklyStandardHours?: number;
  geofenceLatitude?: number | null;
  geofenceLongitude?: number | null;
  geofenceRadius?: number | null;
  squareTeamMemberId?: string | null;
  gustoEmployeeId?: string | null;
  adpEmployeeId?: string | null;
  hasAppAccess?: boolean;
  kioskPin?: string;
  gclid?: string;
  hiringPacketStatus?: {
    w4Completed: boolean;
    i9Completed: boolean;
    directDepositCompleted: boolean;
    handbookSigned: boolean;
    idUploaded: boolean;
    completedAt?: string;
  };
  mfaEnabled?: boolean;
  mfaSecret?: string;
  allowedLocationIds?: string[];
  customerPortalRole?: 'corporate' | 'regional' | 'branch';
  assignedDivisions?: string[];
  subcontractorId?: string | null;
}
