
import { ProposalPreset } from '@types';

export const HVAC_MASTER_BOOK: Omit<ProposalPreset, 'id' | 'organizationId'>[] = [
    // --- 1. DIAGNOSTICS & DISPATCH ---
    { name: 'Diagnostic - Level 1 (Standard)', description: 'Standard troubleshooting for a single residential split system or package unit during business hours. Includes travel and initial assessment.', baseCost: 0, avgLabor: 1.0, category: 'Diagnostics' },
    { name: 'Diagnostic - Level 2 (Advanced/Electronic)', description: 'In-depth troubleshooting for communicating systems, inverters, or complex low-voltage shorts requiring wire tracing.', baseCost: 0, avgLabor: 1.75, category: 'Diagnostics' },
    { name: 'Diagnostic - Level 3 (Multi-System/Commercial)', description: 'Diagnostic evaluation for commercial rooftop units (RTU) or residential sites with 3+ systems.', baseCost: 0, avgLabor: 2.5, category: 'Diagnostics' },
    { name: 'Diagnostic - After Hours / Emergency', description: 'Priority dispatch and diagnosis performed on nights, weekends, or holidays.', baseCost: 0, avgLabor: 1.5, category: 'Diagnostics' },
    { name: 'Leak Search - Level 1 (Electronic)', description: 'Electronic refrigerant leak detection of accessible components (Condenser, Evaporator, exposed Line set).', baseCost: 0, avgLabor: 1.0, category: 'Diagnostics' },
    { name: 'Leak Search - Level 2 (Nitrogen/Dye)', description: 'Nitrogen pressure test and UV dye injection to locate micro-leaks. Includes return visit for dye check.', baseCost: 45, avgLabor: 2.5, category: 'Diagnostics' },
    { name: 'Leak Search - Level 3 (Isolation)', description: 'Cutting and brazing to isolate condenser, evaporator, and lineset for individual pressure decay testing.', baseCost: 85, avgLabor: 4.0, category: 'Diagnostics' },
    { name: 'Combustion Analysis (Furnace)', description: 'Digital analysis of flue gases to verify O2, CO, CO2, and efficiency levels. Checks for heat exchanger safety.', baseCost: 5, avgLabor: 1.0, category: 'Heating' },
    { name: 'Static Pressure Test & Airflow Audit', description: 'Measure Total External Static Pressure (TESP) and pressure drops across filter/coil to diagnose airflow issues.', baseCost: 0, avgLabor: 1.25, category: 'Airflow' },
    { name: 'Thermal Imaging Inspection', description: 'Infrared scan of ductwork, insulation, and electrical panels to identify heat loss/gain or hotspots.', baseCost: 0, avgLabor: 0.75, category: 'Diagnostics' },
    { name: 'Manual J Load Calculation (Room)', description: 'Calculation for a single room addition or problem area.', baseCost: 0, avgLabor: 1.5, category: 'Diagnostics' },
    { name: 'Manual J Load Calculation (Whole House)', description: 'Full heat load calculation for system sizing.', baseCost: 0, avgLabor: 3.0, category: 'Diagnostics' },

    // --- 2. CAPACITORS & START GEAR ---
    { name: 'Capacitor - Single Run (3-15 MFD)', description: 'Replace failed run capacitor for fan motors.', baseCost: 8, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Single Run (20-40 MFD)', description: 'Replace run capacitor for compressor circuits (Single Value).', baseCost: 12, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (30/3 - 30/5 MFD)', description: 'Replace dual run capacitor for 1.5-2 ton systems.', baseCost: 15, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (35/3 - 35/5 MFD)', description: 'Replace dual run capacitor for 2-2.5 ton systems.', baseCost: 16, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (40/3 - 40/5 MFD)', description: 'Replace dual run capacitor for 2.5-3 ton systems.', baseCost: 18, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (45/3 - 45/5 MFD)', description: 'Replace dual run capacitor for 3-3.5 ton systems.', baseCost: 20, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (50/5 - 55/5 MFD)', description: 'Replace dual run capacitor for 3.5-4 ton systems.', baseCost: 24, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (60/5 - 70/5 MFD)', description: 'Replace dual run capacitor for 4-5 ton systems.', baseCost: 28, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (80/5 - 80/7.5 MFD)', description: 'Replace high capacity dual run capacitor for high efficiency systems.', baseCost: 35, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - USA Made (Turbo 200 Universal)', description: 'Install premium American-made multi-tap capacitor (5 Year Warranty).', baseCost: 75, avgLabor: 0.75, category: 'Electrical' },
    { name: 'Capacitor - USA Made (Turbo 200X Universal)', description: 'Install premium high-capacity American-made multi-tap capacitor.', baseCost: 95, avgLabor: 0.75, category: 'Electrical' },
    { name: 'Hard Start Kit - 2-Wire (PTC)', description: 'Install positive temperature coefficient assist kit (Standard).', baseCost: 25, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Hard Start Kit - 3-Wire (Potential Relay/5-2-1)', description: 'Install heavy duty potential relay start kit for compressor protection.', baseCost: 65, avgLabor: 0.75, category: 'Electrical' },
    { name: 'Compressor Saver / Soft Start Kit', description: 'Install electronic soft starter to reduce inrush current (Great for generators).', baseCost: 280, avgLabor: 1.5, category: 'Electrical' },

    // --- 3. CONTACTORS, RELAYS & TRANSFORMERS ---
    { name: 'Contactor - 1 Pole (30 Amp)', description: 'Replace standard single pole condenser contactor.', baseCost: 15, avgLabor: 0.75, category: 'Electrical' },
    { name: 'Contactor - 1.5 Pole (40 Amp)', description: 'Replace heavy duty contactor with shunt.', baseCost: 22, avgLabor: 0.75, category: 'Electrical' },
    { name: 'Contactor - 2 Pole (30 Amp)', description: 'Replace standard double pole contactor.', baseCost: 20, avgLabor: 0.75, category: 'Electrical' },
    { name: 'Contactor - 2 Pole (40 Amp)', description: 'Replace heavy duty double pole contactor.', baseCost: 28, avgLabor: 0.75, category: 'Electrical' },
    { name: 'Contactor - 3 Pole (40-60 Amp)', description: 'Replace 3-phase commercial contactor.', baseCost: 65, avgLabor: 1.0, category: 'Electrical' },
    { name: 'Transformer - 40VA (Foot Mount)', description: 'Replace standard 24V control transformer.', baseCost: 25, avgLabor: 1.0, category: 'Electrical' },
    { name: 'Transformer - 75VA (Heavy Duty)', description: 'Replace high capacity control transformer.', baseCost: 45, avgLabor: 1.0, category: 'Electrical' },
    { name: 'Fan Center Relay (DPDT)', description: 'Replace indoor blower control relay/center.', baseCost: 35, avgLabor: 1.0, category: 'Electrical' },
    { name: 'Sequencer - 1 Switch', description: 'Replace single stage electric heat sequencer.', baseCost: 20, avgLabor: 0.75, category: 'Heating' },
    { name: 'Sequencer - 2 Switch', description: 'Replace dual stage electric heat sequencer.', baseCost: 35, avgLabor: 1.0, category: 'Heating' },
    { name: 'Relay - General Purpose (Cube)', description: 'Replace isolation or switching relay (SPDT/DPDT).', baseCost: 15, avgLabor: 0.75, category: 'Electrical' },
    { name: 'Time Delay Relay (Delay on Break)', description: 'Install compressor short-cycle protection timer.', baseCost: 25, avgLabor: 0.75, category: 'Electrical' },

    // --- 4. MOTORS (CONDENSER & BLOWER) ---
    { name: 'Condenser Fan Motor - PSC (1/6 - 1/4 HP)', description: 'Replace standard outdoor fan motor (825/1075 RPM). Includes Capacitor.', baseCost: 145, avgLabor: 1.5, category: 'Cooling' },
    { name: 'Condenser Fan Motor - PSC (1/3 - 1/2 HP)', description: 'Replace high capacity outdoor fan motor. Includes Capacitor.', baseCost: 185, avgLabor: 1.5, category: 'Cooling' },
    { name: 'Condenser Fan Motor - ECM (Universal)', description: 'Replace outdoor ECM motor with universal rescue motor.', baseCost: 350, avgLabor: 2.0, category: 'Cooling' },
    { name: 'Condenser Fan Motor - OEM Variable', description: 'Replace proprietary communicating outdoor motor.', baseCost: 650, avgLabor: 2.5, category: 'Cooling' },
    { name: 'Fan Blade - 2 Blade', description: 'Replace bent or damaged condenser fan blade.', baseCost: 65, avgLabor: 1.0, category: 'Cooling' },
    { name: 'Fan Blade - 3/4 Blade', description: 'Replace multi-wing condenser fan blade.', baseCost: 95, avgLabor: 1.0, category: 'Cooling' },
    { name: 'Rain Shield / Slinger', description: 'Install shaft water protection on motor.', baseCost: 5, avgLabor: 0.25, category: 'Cooling' },
    { name: 'Blower Motor - PSC (1/3 - 1/2 HP)', description: 'Replace standard indoor blower motor. Includes Capacitor.', baseCost: 165, avgLabor: 2.0, category: 'Heating' },
    { name: 'Blower Motor - PSC (3/4 - 1 HP)', description: 'Replace heavy duty indoor blower motor. Includes Capacitor.', baseCost: 220, avgLabor: 2.0, category: 'Heating' },
    { name: 'Blower Motor - ECM Constant Torque (X13)', description: 'Replace programmed constant torque blower motor (OEM or Rescue).', baseCost: 450, avgLabor: 2.5, category: 'Heating' },
    { name: 'Blower Motor - ECM Variable Speed', description: 'Replace communicating variable speed indoor motor (OEM).', baseCost: 850, avgLabor: 3.0, category: 'Heating' },
    { name: 'Blower Motor Module Only', description: 'Replace ECM control head on variable speed motor.', baseCost: 450, avgLabor: 1.5, category: 'Heating' },
    { name: 'Blower Wheel - Standard', description: 'Replace squirrel cage blower wheel (up to 12x12).', baseCost: 110, avgLabor: 2.5, category: 'Airflow' },
    { name: 'Blower Wheel - Heavy Duty/Large', description: 'Replace large commercial or heavy duty blower wheel.', baseCost: 185, avgLabor: 3.0, category: 'Airflow' },
    { name: 'Blower Housing Mount Repair', description: 'Repair loose or broken motor mount bracket.', baseCost: 25, avgLabor: 1.5, category: 'Airflow' },
    { name: 'Belt Replacement - A Type', description: 'Replace fan belt and adjust tension.', baseCost: 15, avgLabor: 0.75, category: 'Maintenance' },
    { name: 'Belt Replacement - B Type', description: 'Replace heavy duty fan belt and adjust tension.', baseCost: 25, avgLabor: 0.75, category: 'Maintenance' },
    { name: 'Pulley / Sheave Replacement', description: 'Replace worn motor or blower sheave and align.', baseCost: 65, avgLabor: 1.5, category: 'Airflow' },
    { name: 'Bearings - Pillow Block (Set)', description: 'Replace shaft bearings on commercial blower.', baseCost: 85, avgLabor: 2.5, category: 'Airflow' },

    // --- 5. COMPRESSOR & REFRIGERANT CIRCUIT ---
    { name: 'Compressor - 1.5 - 2.5 Ton (Scroll)', description: 'Replace hermetic scroll compressor. Includes Drier & Cap/Start components.', baseCost: 750, avgLabor: 6.0, category: 'Cooling' },
    { name: 'Compressor - 3 - 3.5 Ton (Scroll)', description: 'Replace hermetic scroll compressor. Includes Drier & Cap/Start components.', baseCost: 950, avgLabor: 6.0, category: 'Cooling' },
    { name: 'Compressor - 4 - 5 Ton (Scroll)', description: 'Replace hermetic scroll compressor. Includes Drier & Cap/Start components.', baseCost: 1200, avgLabor: 7.0, category: 'Cooling' },
    { name: 'Compressor - Rotary (1-2 Ton)', description: 'Replace rotary compressor for mini-split or window unit.', baseCost: 650, avgLabor: 5.0, category: 'Cooling' },
    { name: 'Compressor - 2 Stage (Copeland Ultratech)', description: 'Replace unloading 2-stage scroll compressor.', baseCost: 1600, avgLabor: 8.0, category: 'Cooling' },
    { name: 'Compressor - Inverter Driven', description: 'Replace variable speed DC inverter compressor (OEM).', baseCost: 2200, avgLabor: 9.0, category: 'Cooling' },
    { name: 'Acid Clean-up / Burnout Kit', description: 'Install suction line filter drier and add acid scavenger after burnout.', baseCost: 125, avgLabor: 3.0, category: 'Cooling' },
    { name: 'Service Valve - Liquid Line', description: 'Replace leaking liquid line service valve.', baseCost: 65, avgLabor: 4.0, category: 'Cooling' },
    { name: 'Service Valve - Suction Line', description: 'Replace leaking suction line service valve.', baseCost: 95, avgLabor: 4.5, category: 'Cooling' },
    { name: 'Schrader Core Replacement (Under Pressure)', description: 'Replace leaking core using removal tool.', baseCost: 5, avgLabor: 0.5, category: 'Cooling' },
    { name: 'Service Port Cap - Brass (Locking)', description: 'Replace missing or stripped service port cap.', baseCost: 8, avgLabor: 0.1, category: 'Cooling' },
    { name: 'Filter Drier - Liquid Line (Weld-in)', description: 'Replace liquid line filter drier (up to 3/8").', baseCost: 35, avgLabor: 3.5, category: 'Cooling' },
    { name: 'Filter Drier - Suction Line (Weld-in)', description: 'Install or replace suction line filter drier.', baseCost: 65, avgLabor: 4.0, category: 'Cooling' },
    { name: 'TXV Replacement (Bolt-on)', description: 'Replace thermal expansion valve (Mechanical). Includes bulb strap and insulation.', baseCost: 145, avgLabor: 5.0, category: 'Cooling' },
    { name: 'TXV Replacement (Weld-on)', description: 'Replace brazed thermal expansion valve.', baseCost: 165, avgLabor: 6.0, category: 'Cooling' },
    { name: 'Piston / Orifice Replacement', description: 'Replace fixed metering device.', baseCost: 15, avgLabor: 3.5, category: 'Cooling' },
    { name: 'Reversing Valve - 2-3 Ton', description: 'Replace 4-way heat pump reversing valve.', baseCost: 180, avgLabor: 7.0, category: 'Cooling' },
    { name: 'Reversing Valve - 3.5-5 Ton', description: 'Replace large 4-way heat pump reversing valve.', baseCost: 240, avgLabor: 7.5, category: 'Cooling' },
    { name: 'Solenoid Coil - Reversing Valve', description: 'Replace failed electromagnetic coil for reversing valve.', baseCost: 35, avgLabor: 1.0, category: 'Electrical' },
    { name: 'Muffler - Discharge Line', description: 'Replace discharge line muffler.', baseCost: 85, avgLabor: 4.0, category: 'Cooling' },
    { name: 'Accumulator - Suction Line', description: 'Replace rusted or restricted suction accumulator.', baseCost: 145, avgLabor: 5.0, category: 'Cooling' },
    { name: 'Coil Repair - U-Bend', description: 'Braze repair of leaking U-bend on coil.', baseCost: 25, avgLabor: 3.0, category: 'Cooling' },
    { name: 'Coil Repair - Aluminum Epoxy', description: 'Epoxy patch repair for aluminum coil leak (Temporary).', baseCost: 45, avgLabor: 2.0, category: 'Cooling' },

    // --- 6. REFRIGERANT HANDLING ---
    { name: 'Refrigerant - R410A (Per Pound)', description: 'Supply and charge R410A refrigerant.', baseCost: 12, avgLabor: 0.2, category: 'Cooling' },
    { name: 'Refrigerant - R22 (Per Pound)', description: 'Supply and charge R22 (Reclaimed/Virgin). Market price variable.', baseCost: 95, avgLabor: 0.2, category: 'Cooling' },
    { name: 'Refrigerant - R407C / R422 (Per Pound)', description: 'Supply and charge R22 drop-in replacement.', baseCost: 35, avgLabor: 0.2, category: 'Cooling' },
    { name: 'Refrigerant - R454B / R32 (A2L)', description: 'Supply and charge next-gen A2L refrigerant.', baseCost: 25, avgLabor: 0.2, category: 'Cooling' },
    { name: 'System Recovery (Up to 5 lbs)', description: 'EPA compliant recovery of refrigerant into tank.', baseCost: 0, avgLabor: 1.5, category: 'Cooling' },
    { name: 'System Recovery (Over 5 lbs)', description: 'Large system recovery.', baseCost: 0, avgLabor: 2.5, category: 'Cooling' },
    { name: 'Nitrogen Pressure Test', description: 'Pressurize system with dry nitrogen to test for leaks.', baseCost: 20, avgLabor: 1.5, category: 'Cooling' },
    { name: 'Vacuum / Evacuation', description: 'Deep vacuum of system to <500 microns.', baseCost: 0, avgLabor: 2.0, category: 'Cooling' },
    { name: 'Chemical Coil Cleaning (Condenser)', description: 'Foaming chemical wash of outdoor coil.', baseCost: 25, avgLabor: 1.0, category: 'Maintenance' },
    { name: 'Chemical Coil Cleaning (Evaporator - In Place)', description: 'No-rinse foam cleaning of indoor coil (if accessible).', baseCost: 35, avgLabor: 1.5, category: 'Maintenance' },
    { name: 'Pull & Clean Evaporator Coil', description: 'Remove coil from cabinet for deep cleaning and reinstall.', baseCost: 65, avgLabor: 5.0, category: 'Maintenance' },

    // --- 7. GAS FURNACE & HEATING ---
    { name: 'Igniter - Hot Surface (Silicon Carbide)', description: 'Replace standard brittle igniter.', baseCost: 30, avgLabor: 1.0, category: 'Heating' },
    { name: 'Igniter - Hot Surface (Nitride Upgrade)', description: 'Upgrade to durable nitride igniter.', baseCost: 65, avgLabor: 1.0, category: 'Heating' },
    { name: 'Spark Igniter / Pilot Assembly', description: 'Replace spark electrode or pilot assembly.', baseCost: 45, avgLabor: 1.5, category: 'Heating' },
    { name: 'Flame Sensor', description: 'Replace flame rectification sensor.', baseCost: 20, avgLabor: 1.0, category: 'Heating' },
    { name: 'Thermocouple (Standing Pilot)', description: 'Replace pilot safety thermocouple.', baseCost: 15, avgLabor: 1.0, category: 'Heating' },
    { name: 'Gas Valve - Single Stage', description: 'Replace standard 24V gas valve.', baseCost: 120, avgLabor: 2.0, category: 'Heating' },
    { name: 'Gas Valve - Two Stage', description: 'Replace 2-stage gas valve.', baseCost: 240, avgLabor: 2.5, category: 'Heating' },
    { name: 'Gas Valve - Modulating', description: 'Replace modulating gas valve (OEM).', baseCost: 380, avgLabor: 3.0, category: 'Heating' },
    { name: 'Inducer Motor - 80% Furnace', description: 'Replace draft inducer assembly.', baseCost: 185, avgLabor: 1.5, category: 'Heating' },
    { name: 'Inducer Motor - 90%+ Furnace', description: 'Replace condensing furnace inducer assembly.', baseCost: 320, avgLabor: 2.0, category: 'Heating' },
    { name: 'Pressure Switch - Single', description: 'Replace air proving pressure switch.', baseCost: 35, avgLabor: 1.0, category: 'Heating' },
    { name: 'Pressure Switch - Dual/Assembly', description: 'Replace dual pressure switch assembly.', baseCost: 65, avgLabor: 1.25, category: 'Heating' },
    { name: 'Limit Switch - Main', description: 'Replace high limit safety switch.', baseCost: 25, avgLabor: 1.0, category: 'Heating' },
    { name: 'Rollout Switch (Manual Reset)', description: 'Replace flame rollout switch.', baseCost: 20, avgLabor: 1.0, category: 'Heating' },
    { name: 'Control Board - Universal', description: 'Replace integrated furnace control (IFC) with universal board.', baseCost: 145, avgLabor: 2.0, category: 'Heating' },
    { name: 'Control Board - OEM', description: 'Replace proprietary OEM furnace board.', baseCost: 280, avgLabor: 2.0, category: 'Heating' },
    { name: 'Gas Flex & Shut-off Valve', description: 'Replace gas connector and ball valve.', baseCost: 35, avgLabor: 1.5, category: 'Heating' },
    { name: 'Flue Pipe Repair (Metal)', description: 'Replace section of rusted single wall flue pipe.', baseCost: 45, avgLabor: 1.5, category: 'Heating' },
    { name: 'Flue Pipe Repair (PVC)', description: 'Repair PVC venting for condensing furnace.', baseCost: 25, avgLabor: 1.5, category: 'Heating' },

    // --- 8. ELECTRIC HEAT ---
    { name: 'Heat Strip Kit - 5kW', description: 'Replace 5kW resistive heater element.', baseCost: 75, avgLabor: 1.5, category: 'Heating' },
    { name: 'Heat Strip Kit - 8-10kW', description: 'Replace 10kW resistive heater element.', baseCost: 120, avgLabor: 2.0, category: 'Heating' },
    { name: 'Heat Strip Kit - 15-20kW', description: 'Replace large heater package.', baseCost: 180, avgLabor: 2.5, category: 'Heating' },
    { name: 'Limit Switch - Heat Strip', description: 'Replace thermal limit on electric heater.', baseCost: 25, avgLabor: 1.0, category: 'Heating' },
    { name: 'Thermal Fuse - Link', description: 'Replace fusible link safety.', baseCost: 15, avgLabor: 1.0, category: 'Heating' },

    // --- 9. THERMOSTATS & CONTROLS ---
    { name: 'Thermostat - Non-Programmable', description: 'Install basic digital thermostat (Pro1/Honeywell).', baseCost: 45, avgLabor: 1.0, category: 'Accessories' },
    { name: 'Thermostat - Programmable (5-1-1)', description: 'Install 7-day or 5-1-1 programmable thermostat.', baseCost: 65, avgLabor: 1.0, category: 'Accessories' },
    { name: 'Thermostat - Wi-Fi (Sensi/T6)', description: 'Install smart thermostat requiring C-wire or kit.', baseCost: 140, avgLabor: 1.5, category: 'Accessories' },
    { name: 'Thermostat - Premium Wi-Fi (Ecobee/Nest)', description: 'Install premium smart thermostat with sensor setup.', baseCost: 240, avgLabor: 2.0, category: 'Accessories' },
    { name: 'Thermostat Wire - New Run', description: 'Fish new 18/5 or 18/8 thermostat wire (up to 30ft).', baseCost: 25, avgLabor: 2.5, category: 'Electrical' },
    { name: 'Float Switch - Inline (SS1)', description: 'Install condensate safety switch in drain line.', baseCost: 35, avgLabor: 1.0, category: 'Accessories' },
    { name: 'Float Switch - Pan (SS2)', description: 'Install condensate safety switch in emergency pan.', baseCost: 30, avgLabor: 1.0, category: 'Accessories' },
    { name: 'Wet Switch / Flood Sensor', description: 'Install puck-style water sensor in pan.', baseCost: 65, avgLabor: 1.0, category: 'Accessories' },
    { name: 'Zone Board Replacement', description: 'Replace zone control panel.', baseCost: 180, avgLabor: 2.0, category: 'Electrical' },
    { name: 'Zone Damper Motor', description: 'Replace actuator on zone damper.', baseCost: 120, avgLabor: 1.5, category: 'Electrical' },

    // --- 10. IAQ & FILTRATION ---
    { name: 'Filter - 1" Pleated (Supply & Install)', description: 'Replace standard 1" filter.', baseCost: 8, avgLabor: 0.25, category: 'Maintenance' },
    { name: 'Filter - Media 4" (Supply & Install)', description: 'Replace 4-5" media filter (Aprilaire/Honeywell).', baseCost: 45, avgLabor: 0.25, category: 'Maintenance' },
    { name: 'UV Light - Bulb Replacement', description: 'Replace annual UV bulb.', baseCost: 65, avgLabor: 0.5, category: 'Maintenance' },
    { name: 'UV Light System - Coil Mount', description: 'Install new single bulb UV stick light.', baseCost: 180, avgLabor: 1.5, category: 'Accessories' },
    { name: 'Air Scrubber / Ionizer', description: 'Install duct-mounted active air purifier (e.g. Reme Halo/Air Scrubber).', baseCost: 550, avgLabor: 1.5, category: 'Accessories' },
    { name: 'Humidifier Pad Replacement', description: 'Replace water panel in humidifier.', baseCost: 18, avgLabor: 0.5, category: 'Maintenance' },
    { name: 'Humidifier Installation - Bypass', description: 'Install whole-home bypass humidifier.', baseCost: 280, avgLabor: 4.0, category: 'Accessories' },
    { name: 'Dehumidifier Installation (Whole Home)', description: 'Install ducted dehumidifier system.', baseCost: 1400, avgLabor: 6.0, category: 'Accessories' },

    // --- 11. PLUMBING (CONDENSATE) ---
    { name: 'Condensate Pump - Standard', description: 'Replace 120V or 230V condensate removal pump.', baseCost: 65, avgLabor: 1.0, category: 'Plumbing' },
    { name: 'Clear Drain Line - Nitrogen/Vacuum', description: 'Clear blockage in primary drain line.', baseCost: 5, avgLabor: 1.0, category: 'Plumbing' },
    { name: 'Condensate Trap - Replace', description: 'Re-pipe P-trap with cleanout.', baseCost: 15, avgLabor: 1.0, category: 'Plumbing' },
    { name: 'Emergency Drain Pan - Install', description: 'Slide new plastic or metal pan under unit (if accessible).', baseCost: 65, avgLabor: 2.0, category: 'Plumbing' },

    // --- 12. DUCTWORK & AIRFLOW ---
    { name: 'Duct Repair - Single Splice', description: 'Repair torn or disconnected flex duct.', baseCost: 25, avgLabor: 1.5, category: 'Airflow' },
    { name: 'Duct Replacement - 6" Run', description: 'Replace up to 25ft of 6" flex duct.', baseCost: 65, avgLabor: 2.5, category: 'Airflow' },
    { name: 'Duct Replacement - 8" Run', description: 'Replace up to 25ft of 8" flex duct.', baseCost: 85, avgLabor: 2.5, category: 'Airflow' },
    { name: 'Duct Replacement - 10"+ Run', description: 'Replace large return or supply flex.', baseCost: 120, avgLabor: 3.0, category: 'Airflow' },
    { name: 'Supply Register - Replacement', description: 'Replace stamped metal ceiling or floor register.', baseCost: 20, avgLabor: 0.5, category: 'Airflow' },
    { name: 'Return Grill - Replacement', description: 'Replace filter grille assembly.', baseCost: 45, avgLabor: 1.0, category: 'Airflow' },
    { name: 'Duct Sealing - Mastic (Per System)', description: 'Seal accessible plenums and start collars with mastic.', baseCost: 45, avgLabor: 3.0, category: 'Airflow' },
    { name: 'Dryer Vent Cleaning', description: 'Brush and vacuum dryer exhaust vent.', baseCost: 0, avgLabor: 1.5, category: 'Maintenance' },

    // --- 13. SYSTEM REPLACEMENT (Estimates) ---
    { name: 'System Install - 14 SEER 2 Ton (Estimate)', description: 'Base efficiency complete system replacement.', baseCost: 2200, avgLabor: 16.0, category: 'Other' },
    { name: 'System Install - 16 SEER 3 Ton (Estimate)', description: 'High efficiency complete system replacement.', baseCost: 3200, avgLabor: 16.0, category: 'Other' },
    { name: 'System Install - 18+ SEER Inverter (Estimate)', description: 'Premium inverter system replacement.', baseCost: 5500, avgLabor: 20.0, category: 'Other' },
    { name: 'Furnace Swap - 80% (Estimate)', description: 'Gas furnace replacement only.', baseCost: 900, avgLabor: 8.0, category: 'Heating' },
    { name: 'Condenser Swap - 14 SEER (Estimate)', description: 'Outdoor unit replacement only.', baseCost: 1400, avgLabor: 6.0, category: 'Cooling' },
];
