import { ProposalPreset } from 'types';

export const HVAC_MASTER_BOOK: Omit<ProposalPreset, 'id' | 'organizationId'>[] = [
    // 1. DIAGNOSTICS & FIELD TESTING
    { name: 'Diagnostic - Level 1 (Standard)', description: 'Standard troubleshooting for a single residential split system or package unit during business hours.', baseCost: 0, avgLabor: 1, category: 'Diagnostics' },
    { name: 'Diagnostic - Level 2 (Multi-System)', description: 'Diagnostic evaluation for residential sites with more than one HVAC system.', baseCost: 0, avgLabor: 1.75, category: 'Diagnostics' },
    { name: 'Diagnostic - After Hours Emergency', description: 'Priority dispatch and diagnosis performed outside standard business hours.', baseCost: 0, avgLabor: 1.5, category: 'Diagnostics' },
    { name: 'Static Pressure Test & Duct Audit', description: 'Measure Total External Static Pressure (TESP) to diagnose airflow restrictions or blower issues.', baseCost: 0, avgLabor: 1.25, category: 'Airflow' },
    { name: 'Combustion Analysis (Furnace)', description: 'Perform digital combustion analysis to check for heat exchanger integrity and CO safety.', baseCost: 5, avgLabor: 1, category: 'Heating' },
    { name: 'Leak Search - Electronic (Accessible)', description: 'Electronic refrigerant leak detection of all accessible components (Condenser, Evaporator, Line set).', baseCost: 0, avgLabor: 1.5, category: 'Diagnostics' },
    { name: 'Leak Search - Nitrogen Isolation', description: 'Pressure test isolation of components including recovery of refrigerant to pinpoint leak location.', baseCost: 110, avgLabor: 4, category: 'Diagnostics' },
    { name: 'Airflow Balancing - Per Room', description: 'Adjust dampers and registers to optimize airflow distribution throughout the home.', baseCost: 0, avgLabor: 0.5, category: 'Airflow' },
    { name: 'Thermal Imaging Inspection', description: 'Infrared scan of ductwork and equipment to identify heat gain/loss and insulation failures.', baseCost: 0, avgLabor: 1, category: 'Diagnostics' },
    { name: 'Thermostat Wiring Troubleshooting', description: 'Locate and repair shorts or breaks in low voltage control wiring.', baseCost: 5, avgLabor: 1.5, category: 'Electrical' },

    // 2. CAPACITORS (SINGLE & DUAL RUN)
    { name: 'Capacitor - Single Run (5-15 MFD)', description: 'Replacement of standard run capacitor for fan motors.', baseCost: 12, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Single Run (20-45 MFD)', description: 'Replacement of run capacitor for compressor circuits.', baseCost: 18, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (35/5 MFD)', description: 'Standard 1.5 - 2.0 ton condenser dual run capacitor.', baseCost: 22, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (40/5 MFD)', description: 'Standard 2.5 ton condenser dual run capacitor.', baseCost: 24, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (45/5 MFD)', description: 'Standard 3.0 ton condenser dual run capacitor.', baseCost: 26, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (50/5 MFD)', description: 'Standard 3.5 ton condenser dual run capacitor.', baseCost: 28, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (55/5 MFD)', description: 'Standard 4.0 ton condenser dual run capacitor.', baseCost: 32, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (60/5 MFD)', description: 'Standard 5.0 ton condenser dual run capacitor.', baseCost: 35, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - Dual Run (70/5 - 80/10 MFD)', description: 'High capacity heavy duty condenser dual run capacitor.', baseCost: 45, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Capacitor - AMRAD Turbo 200 (Universal)', description: 'Universal long-life American-made capacitor with 5-year warranty.', baseCost: 85, avgLabor: 0.75, category: 'Electrical' },
    { name: 'Capacitor - AMRAD Turbo 200 Mini', description: 'Universal fan motor capacitor for all single-value needs.', baseCost: 65, avgLabor: 0.75, category: 'Electrical' },

    // 3. CONTACTORS & ELECTRICAL PARTS
    { name: 'Contactor - 1 Pole (25-30 Amp)', description: 'Standard residential condenser contactor replacement.', baseCost: 18, avgLabor: 0.75, category: 'Electrical' },
    { name: 'Contactor - 2 Pole (25-40 Amp)', description: 'Heavy duty residential condenser contactor replacement.', baseCost: 25, avgLabor: 0.75, category: 'Electrical' },
    { name: 'Contactor - 3 Pole (30-50 Amp)', description: 'Commercial or specialized residential 3-phase contactor.', baseCost: 85, avgLabor: 1.25, category: 'Electrical' },
    { name: 'Transformer - 40VA (Multi-Tap)', description: 'Replace failed 24V control power transformer.', baseCost: 28, avgLabor: 1, category: 'Electrical' },
    { name: 'Transformer - 75VA (Heavy Duty)', description: 'Replace high-capacity control power transformer.', baseCost: 45, avgLabor: 1, category: 'Electrical' },
    { name: 'Hard Start Kit - Potential Relay Type', description: '5-2-1 Compressor protection and start assistance kit.', baseCost: 85, avgLabor: 1, category: 'Electrical' },
    { name: 'Hard Start Kit - PTC Type', description: 'Economic compressor start assistance.', baseCost: 35, avgLabor: 0.5, category: 'Electrical' },
    { name: 'Defrost Control Board - Universal', description: 'Replace failed heat pump defrost logic board.', baseCost: 165, avgLabor: 2, category: 'Electrical' },
    { name: 'Fan Center Relay', description: 'Replace indoor blower control relay.', baseCost: 35, avgLabor: 1, category: 'Electrical' },
    { name: 'Time Delay Relay', description: 'Add or replace compressor short-cycle protection timer.', baseCost: 25, avgLabor: 1, category: 'Electrical' },
    { name: 'Condenser Whip - 6ft Non-Metallic', description: 'Replace weathered or shorted condenser power whip.', baseCost: 42, avgLabor: 1, category: 'Electrical' },
    { name: 'Disconnect Box - 60 Amp Non-Fused', description: 'Replace outdoor electrical safety disconnect.', baseCost: 38, avgLabor: 1.25, category: 'Electrical' },
    { name: 'Disconnect Box - 60 Amp Fused', description: 'Replace outdoor disconnect with internal fuse protection.', baseCost: 55, avgLabor: 1.5, category: 'Electrical' },
    { name: 'Control Fuse (3-5 Amp)', description: 'Locate short and replace blown low voltage fuse.', baseCost: 2, avgLabor: 0.5, category: 'Electrical' },

    // 4. FAN MOTORS & BLOWERS
    { name: 'Condenser Fan Motor - PSC 1/6 HP', description: 'Replace standard outdoor fan motor.', baseCost: 135, avgLabor: 1.5, category: 'Electrical' },
    { name: 'Condenser Fan Motor - PSC 1/4 HP', description: 'Replace standard outdoor fan motor.', baseCost: 155, avgLabor: 1.5, category: 'Electrical' },
    { name: 'Condenser Fan Motor - PSC 1/3 HP', description: 'Replace high capacity outdoor fan motor.', baseCost: 185, avgLabor: 1.5, category: 'Electrical' },
    { name: 'Condenser Fan Motor - ECM (X13 Style)', description: 'Replace high efficiency constant torque outdoor motor.', baseCost: 380, avgLabor: 2, category: 'Electrical' },
    { name: 'Condenser Fan Motor - OEM Variable Speed', description: 'Replace unit-specific communicating inverter motor.', baseCost: 650, avgLabor: 2.5, category: 'Electrical' },
    { name: 'Blower Motor - PSC 1/3 HP', description: 'Replace standard indoor fan motor.', baseCost: 165, avgLabor: 2, category: 'Electrical' },
    { name: 'Blower Motor - PSC 1/2 HP', description: 'Replace standard indoor fan motor.', baseCost: 195, avgLabor: 2, category: 'Electrical' },
    { name: 'Blower Motor - PSC 3/4 HP', description: 'Replace heavy duty indoor fan motor.', baseCost: 245, avgLabor: 2.5, category: 'Electrical' },
    { name: 'Blower Motor - ECM Constant Torque', description: 'Replace digital indoor fan motor (Programmed).', baseCost: 420, avgLabor: 2.5, category: 'Electrical' },
    { name: 'Blower Motor - ECM Variable Speed', description: 'Replace premium communicating indoor motor.', baseCost: 750, avgLabor: 3, category: 'Electrical' },
    { name: 'Blower Wheel - Standard 10x10', description: 'Replace unbalanced or corroded indoor fan wheel.', baseCost: 95, avgLabor: 2.5, category: 'Airflow' },
    { name: 'Blower Housing Assembly - Full', description: 'Replace entire indoor fan scroll and housing.', baseCost: 320, avgLabor: 3.5, category: 'Airflow' },
    { name: 'Fan Blade - Condenser (Standard)', description: 'Replace bent or damaged outdoor fan propeller.', baseCost: 85, avgLabor: 1.5, category: 'Airflow' },

    // 5. GAS HEATING COMPONENTS
    { name: 'Igniter - Silicon Carbide', description: 'Replace standard hot surface igniter.', baseCost: 28, avgLabor: 1, category: 'Heating' },
    { name: 'Igniter - Nitride Upgrade', description: 'Replace with long-life durable nitride igniter.', baseCost: 65, avgLabor: 1, category: 'Heating' },
    { name: 'Flame Sensor - Cleaning', description: 'Precision cleaning of carbon deposits on rectification probe.', baseCost: 5, avgLabor: 0.75, category: 'Heating' },
    { name: 'Flame Sensor - Replacement', description: 'Replace worn or broken flame rectification probe.', baseCost: 22, avgLabor: 1, category: 'Heating' },
    { name: 'Gas Valve - Single Stage (Universal)', description: 'Replace failed 24V gas control valve.', baseCost: 145, avgLabor: 2, category: 'Heating' },
    { name: 'Gas Valve - Two Stage (OEM)', description: 'Replace unit-specific two-stage gas control.', baseCost: 320, avgLabor: 2.5, category: 'Heating' },
    { name: 'Inducer Draft Motor - 80% Furnace', description: 'Replace standard exhaust blower assembly.', baseCost: 210, avgLabor: 1.5, category: 'Heating' },
    { name: 'Inducer Draft Motor - 90% High Efficiency', description: 'Replace high efficiency condensing exhaust blower.', baseCost: 385, avgLabor: 2, category: 'Heating' },
    { name: 'Furnace Control Board - Universal', description: 'Replace logic board for standard ignition control.', baseCost: 175, avgLabor: 2, category: 'Heating' },
    { name: 'Furnace Control Board - OEM', description: 'Replace unit-specific proprietary control board.', baseCost: 350, avgLabor: 2, category: 'Heating' },
    { name: 'Pressure Switch - Single Stage', description: 'Replace safety switch for draft verification.', baseCost: 45, avgLabor: 1, category: 'Heating' },
    { name: 'Limit Switch - Primary', description: 'Replace high temperature safety switch.', baseCost: 25, avgLabor: 1, category: 'Heating' },
    { name: 'Limit Switch - Rollout', description: 'Replace safety rollout sensor.', baseCost: 18, avgLabor: 1, category: 'Heating' },
    { name: 'Thermopile / Thermocouple', description: 'Replace pilot safety generator (Standing Pilot).', baseCost: 15, avgLabor: 1, category: 'Heating' },

    // 6. ELECTRIC HEATING COMPONENTS
    { name: 'Heat Strip - 5kW Assembly', description: 'Replace electric backup heat element.', baseCost: 85, avgLabor: 2, category: 'Heating' },
    { name: 'Heat Strip - 10kW Assembly', description: 'Replace electric backup heat element.', baseCost: 145, avgLabor: 2.5, category: 'Heating' },
    { name: 'Sequencer - Single Relay', description: 'Replace staging control for electric heat.', baseCost: 22, avgLabor: 1, category: 'Heating' },
    { name: 'Sequencer - Multi-Relay', description: 'Replace multi-circuit electric heat sequencer.', baseCost: 38, avgLabor: 1.25, category: 'Heating' },
    { name: 'Contactor - Electric Heat', description: 'Replace heavy duty heater contactor.', baseCost: 45, avgLabor: 1.5, category: 'Heating' },

    // 7. REFRIGERATION MECHANICAL
    { name: 'TXV - Expansion Valve (Indoor)', description: 'Replace refrigerant metering device (Includes Recovery/Vac).', baseCost: 185, avgLabor: 6, category: 'Cooling' },
    { name: 'Piston / Orifice - Metering', description: 'Replace fixed orifice metering device.', baseCost: 15, avgLabor: 4, category: 'Cooling' },
    { name: 'Filter Drier - Liquid Line', description: 'Replace system filter drier (Requires refrigerant circuit access).', baseCost: 35, avgLabor: 4, category: 'Cooling' },
    { name: 'Reversing Valve - Heat Pump', description: 'Replace 4-way reversing valve assembly (Major Repair).', baseCost: 280, avgLabor: 8, category: 'Cooling' },
    { name: 'Compressor - 2 Ton Scroll', description: 'Replace failed hermetic compressor.', baseCost: 850, avgLabor: 8, category: 'Cooling' },
    { name: 'Compressor - 3 Ton Scroll', description: 'Replace failed hermetic compressor.', baseCost: 1050, avgLabor: 8, category: 'Cooling' },
    { name: 'Compressor - 5 Ton Scroll', description: 'Replace failed hermetic compressor.', baseCost: 1450, avgLabor: 9, category: 'Cooling' },
    { name: 'Acid Scrubber / Burnout Kit', description: 'Add high-capacity suction line filters to clean circuit after failure.', baseCost: 120, avgLabor: 3, category: 'Cooling' },
    { name: 'Schrader Core - Replacement', description: 'Replace leaking service valve core under pressure.', baseCost: 8, avgLabor: 0.5, category: 'Cooling' },
    { name: 'Service Valve - Liquid/Suction', description: 'Replace failed condenser isolation valve.', baseCost: 110, avgLabor: 5, category: 'Cooling' },

    // 8. AIRFLOW & IAQ
    { name: 'Thermostat - Basic Digital', description: 'Supply and install simple non-programmable control.', baseCost: 45, avgLabor: 1, category: 'Accessories' },
    { name: 'Thermostat - Wi-Fi Programmable', description: 'Supply and install smart connected thermostat.', baseCost: 185, avgLabor: 1.5, category: 'Accessories' },
    { name: 'Thermostat - Nest / Ecobee (Customer Provided)', description: 'Install and configure smart control provided by client.', baseCost: 0, avgLabor: 1.5, category: 'Accessories' },
    { name: 'UV Germicidal Light - Single Bulb', description: 'Install air purification lamp in evaporator coil area.', baseCost: 175, avgLabor: 1.5, category: 'Accessories' },
    { name: 'Air Scrubber - Active Oxidation', description: 'Install whole-home active air purification system.', baseCost: 550, avgLabor: 2, category: 'Accessories' },
    { name: 'Media Filter Cabinet (4-5 inch)', description: 'Install high-capacity deep pleated filter housing.', baseCost: 285, avgLabor: 3, category: 'Airflow' },
    { name: 'EZ-Trap Condensate Overflow Switch', description: 'Add safety water level protection for drain line.', baseCost: 35, avgLabor: 1, category: 'Plumbing' },
    { name: 'Condensate Pump - Standard', description: 'Replace pump for high efficiency or attic units.', baseCost: 75, avgLabor: 1.5, category: 'Plumbing' },
    { name: 'Drain Line - Clearing / Nitrogen Flush', description: 'Use high pressure nitrogen to clear slime/debris from line.', baseCost: 5, avgLabor: 1, category: 'Plumbing' },

    // 9. MAINTENANCE & TUNE-UP
    { name: 'Maintenance - Residential (AC Only)', description: 'Comprehensive 21-point inspection and cleaning of cooling system.', baseCost: 15, avgLabor: 1.5, category: 'Maintenance' },
    { name: 'Maintenance - Residential (Heat Pump)', description: 'Full system check of indoor and outdoor components.', baseCost: 15, avgLabor: 2, category: 'Maintenance' },
    { name: 'Maintenance - Gas Furnace Safety', description: 'Check combustion, heat exchanger, and safety limits.', baseCost: 5, avgLabor: 1.25, category: 'Maintenance' },
    { name: 'Evaporator Coil - Non-Detergent Cleaning', description: 'Chemical cleaning of accessible indoor coil.', baseCost: 35, avgLabor: 2.5, category: 'Maintenance' },
    { name: 'Condenser Coil - Professional Cleaning', description: 'Foaming chemical wash of outdoor fins.', baseCost: 25, avgLabor: 1.25, category: 'Maintenance' },
    { name: 'Capacitor - Preventive Replacement', description: 'Replacing weak but operational capacitor during maintenance.', baseCost: 25, avgLabor: 0.5, category: 'Maintenance' },

    // 10. REFRIGERANT SERVICES
    { name: 'Refrigerant - R410A (Per Lb)', description: 'Add 1 pound of R410A refrigerant.', baseCost: 45, avgLabor: 0.2, category: 'Cooling' },
    { name: 'Refrigerant - R22 (Per Lb)', description: 'Add 1 pound of reclaimed R22 refrigerant.', baseCost: 250, avgLabor: 0.2, category: 'Cooling' },
    { name: 'Refrigerant - R454B (Per Lb)', description: 'Add 1 pound of new low-GWP refrigerant.', baseCost: 65, avgLabor: 0.2, category: 'Cooling' },
    { name: 'System Recovery Fee', description: 'Environmentally safe removal and storage of existing refrigerant.', baseCost: 0, avgLabor: 2, category: 'Cooling' },
    { name: 'Triple Evacuation / Deep Vacuum', description: 'Evacuation of system to < 500 microns after repair.', baseCost: 0, avgLabor: 3.5, category: 'Cooling' },
    { name: 'Nitrogen Pressure Test (Dry)', description: 'Pressure testing to verify seal after major mechanical repair.', baseCost: 25, avgLabor: 1.5, category: 'Cooling' },
];
